language: objective-c
compiler:
- clang
before_install:
- brew update
- brew install qt5
- brew link qt5 --force
- brew install libpng
- brew link libpng --force
- brew install openssl
- brew install libssh2
- brew install redis
before_script:
- redis-server --daemonize yes
- cd ./redis-desktop-manager
- sudo chmod 777 configure
- sudo sh ./configure
script: 
  - qmake -v
  - qmake 
  - make clean
  - make -s
  - cd ./../tests/
  - qmake
  - make clean
  - make -s
  - ./../bin/tests/tests -platform minimal -txt
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: always
