language: cpp
dist: bionic
sudo: required

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
    - redis-tools
    - redis-server

services:
  - redis-server

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
       brew update > /dev/null
    && brew install qt5 > /dev/null
    && brew install openssl > /dev/null
    && export PATH=/usr/local/opt/qt5/bin/:$PATH
    ;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then       
       sudo apt-get install qt5-default qtdeclarative5-dev libqt5charts5-dev libssl1.0-dev  -y
       ;
  fi
- qmake -v

script:
  - git submodule update --init --recursive 
  - pushd tests
  - python3 -m pip install -r ../src/py/requirements.txt
  - python3 -m nose -v py_tests
  - qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
  - ./../bin/tests/tests -platform minimal -txt
  - popd
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       pushd src && qmake && make -s -j 2 && popd
       ; 
    fi

after_success:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pushd tests &&
      sudo pip install --upgrade cpp-coveralls &&
      coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e 3rdparty/ -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*
      ;
   fi
