language: cpp
compiler:
  - gcc
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt511
- sudo apt-get update -qq
- sudo apt-get install qt51base qt51imageformats qt51tools qt51xmlpatterns qt51x11extras -y -qq
- uname -m
- export QTDIR=/opt/qt51
- export PATH=$QTDIR/bin:$PATH
- export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
- sudo apt-get install libssl1.0.0 -y -qq
- sudo sh ./vagrant-provision/build_automake.sh
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
- sudo apt-get update
- sudo apt-get install gcc-4.7 -y -qq
- sudo apt-get install g++-4.7 -y -qq
- sudo apt-get install gdb -y -qq
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo rm -f /usr/bin/gcov
- sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-4.7 /usr/bin/g++
- sudo ln -s /usr/bin/gcov-4.7 /usr/bin/gcov
before_script:
- cd ./redis-desktop-manager
- sudo chmod 777 configure
- ./configure > /dev/null
script: 
  - qmake -v
  - qmake
  - make -s
  - cd ./../crashreporter/
  - qmake
  - make -s
  - cd ./../tests/
  - qmake
  - make -s
  - ./../bin/tests/tests -platform minimal -txt
after_success:
  - sudo pip install cpp-coveralls --use-mirrors
  - ./coverage.sh
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: always