os: Visual Studio 2015
version: 0.9.0.{build}
clone_depth: 5
install:
- git submodule update --init --recursive
- set QTDIR=C:\Qt\5.7\msvc2015
- set PATH=%QTDIR%\bin;%PATH%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
- nuget install -Version 1.6.0.2 -OutputDirectory ./3rdparty/qredisclient/3rdparty/windows rmt_libssh2
- nuget install -Version 1.2.8.6 -OutputDirectory ./3rdparty/qredisclient/3rdparty/windows rmt_zlib
- qmake -v

build_script:
- set SRCDIR=%cd%
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./src/version.h
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./3rdparty/crashreporter/src/version.h
- cd ./3rdparty/crashreporter
- qmake CONFIG+=release DESTDIR=%SRCDIR%/bin/windows/release
- nmake /S /NOLOGO release
- cd %SRCDIR%/src
- qmake CONFIG+=release
- nmake /S /NOLOGO release
- cd %SRCDIR%
- copy /y .\bin\windows\release\rdm.exe .\build\windows\installer\resources\rdm.exe
- copy /y .\bin\windows\release\rdm.pdb .\build\windows\installer\resources\rdm.pdb
- copy /y .\3rdparty\qredisclient\3rdparty\windows\rmt_openssl.1.0.2.5\build\native\bin\v140\Win32\Release\dynamic\libeay32.dll .\build\windows\installer\resources\libeay32.dll
- copy /y .\3rdparty\qredisclient\3rdparty\windows\rmt_openssl.1.0.2.5\build\native\bin\v140\Win32\Release\dynamic\ssleay32.dll .\build\windows\installer\resources\ssleay32.dll
- cd build/windows/installer/resources/
- windeployqt --no-translations --compiler-runtime --angle --release --force --qmldir %SRCDIR%/src/qml rdm.exe
- cd %SRCDIR%
- call "C:\\Program Files (x86)\\NSIS\\makensis.exe" /V1 /DVERSION=%APPVEYOR_BUILD_VERSION%  ./build/windows/installer/installer.nsi
test_script:
- echo 'Windows build is used only for installer compilation. Skip tests.'
artifacts:
  - path: 'build/windows/installer/*.exe'
